Introduce static singleton object spying with real-method-call and strict-stub default behaviour
mockito/mockito-scala pull request #392
Opened 2021-08-05 13:21 UTC by DarrenBishop

The new `withObjectSpied[...]` works almost the same as `withObjectMocked[...]` e.g. they are both strict by default, but with the following differences:

Static singleton objects are already complete w.r.t to implementation, so the behaviour proposed here is for real methods to be called; this allows slight tweaks in its original behaviour, rather than having to reimplement in stubs.
Otherwise, `withObjectMocked[...]` can still be used.

Leniency settings are made available via an implicit parameters, with _strict_ semantics enabled by default i.e. implicitly.
I did want to spend more time looking into some leniency-related enums I saw during this work, but thought get the PR out sooner rather than later, as it currently works.
@bbonanno do you think there is some de-duplication that can be done in this area?

Finally re: the version parsing, I wanted to try these changes on some code I am working on for my client;`publishLocal` is annoying development-loop, when working across projects. I tried to use the following in my client `build.sbt`:

```sbt
lazy val scalatest = ProjectRef(file("../../OSS/mockito-scala"), "scalatest")
```

This however lead to errors locating the `version.properties` file; the changes seem to fix that. I can remove if it is considered undesirable, give also the creation of `project/Helpers.scala`

2021-08-06 09:22 UTC, bbonanno requested changes

2021-08-06 09:22 UTC, bbonanno commented on scalatest/src/test/scala/user/org/mockito/MockitoScalaSessionTest.scala
> +//      thrown.getMessage should startWith("Unnecessary stubbings detected")
leftover from debugging something?

2021-08-06 09:22 UTC, bbonanno commented on build.sbt
> +
not sure why you had to do this, I never had issues locally.
The release system is broken on CI, hence the failed builds, @mockitoguy is on it, so we should double-check if we really need this after the releases are working again

2021-08-06 09:22 UTC, bbonanno commented on common/src/main/scala/org/mockito/MockitoAPI.scala
> +  }
Nice :)

2021-08-06 16:18 UTC, DarrenBishop commented on scalatest/src/test/scala/user/org/mockito/MockitoScalaSessionTest.scala
> +//      thrown.getMessage should startWith("Unnecessary stubbings detected")
Yeah, there's a peculiar thing with the error message checked at 365 and [420](https://github.com/mockito/mockito-scala/blob/00a51cf7e24abb287cb66230d57ab3c0362ed851/scalatest/src/test/scala/user/org/mockito/MockitoScalaSessionTest.scala#L420); some how the error starts with a bank line, so have to use include. Very weird.

2021-08-06 19:15 UTC, DarrenBishop commented on build.sbt
> +
Thanks for the update on the CI, I was having a hard time understanding what was going on, if my changes caused failures there, etc.

Locally, however, it works well.

The motivation is, using virgin mockito-scala code in a neighbouring project, without having to wait for SBT twice i.e.  `publishLocal` in mockito-scala and then `update` in client-project (which also must reference `-SNAPSHOT`) for every small change:

`client-project/build.sbt`, where I want to try the new mockito-scala features:
```
name := "client-project"

lazy val scalatest = ProjectRef(file("../../OSS/mockito-scala"), "scalatest")

lazy val cdcCommon = (project in file("client-common"))
  .settings(
    name := "client-common",
    libraryDependencies ++= Seq(...)
  )
  .enablePlugins(BuildInfoPlugin)
  .dependsOn(scalatest)
```

Doing so leads to the following error after `reload`:
```
java.io.FileNotFoundException: version.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at scala.io.Source$.fromFile(Source.scala:57)
	at $bb448bab69b87cd1ed49$.$anonfun$commonSettings$2(build.sbt:33)
	at sbt.internal.util.Init$Value.$anonfun$apply$2(Settings.scala:922)
	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:211)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.io.FileNotFoundException: version.properties (No such file or directory)
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

My reasoning is with the `commonSettings` approach, the settings/tasks get resolved from the context of the subprojects, that is, with files, in their subdirectories.

The `inThisBuild(...)` approach, settings/keys (seem to) get resolved at the root (presumably once) but injected into subproject

My reasoning could well be off, but `inThisBuild(...)` does not trigger the error.

I figured this would be useful for yourself and other contributors, being flexible to different workflows; that said, I am a guest in your house so will revert it.

2021-08-07 00:25 UTC, bbonanno commented on build.sbt
> +
That's fine, I just wanted to be sure you were not trying to solve the CI issue that was also present, no need to revert, the requested changes was about the commented out code in one of the tests

2021-08-15 09:27 UTC, bbonanno approved these changes

2021-08-15 11:27 UTC, bbonanno commented
@DarrenBishop pls rebase, the HEAD of the release/1.x branch has the fix for CI

2021-08-17 15:38 UTC, merged